fix: Use latest Kurtosis style
kurtosis-tech/package-template-repo pull request #4
Opened 2023-09-11 16:18 UTC by mieubrisse

This repo was using the old styles. Now, we use:
- Relative imports
- Starlark-normal args with defults

2023-09-11 16:19 UTC, leeederek requested changes
awesome to see - can you add a note in our "best practices" section to mention that we (kurtosis) strongly prefer folks use relative imports where possible when writing starlark?

2023-09-11 16:26 UTC, leeederek approved these changes
Ah just noticed this is not the mono repo, will approve and create a separate issue to track the best practices docs

2023-09-13 13:05 UTC, adschwartz approved these changes

2023-09-13 13:05 UTC, merged

2023-09-13 13:07 UTC, adschwartz commented on static-files/config.json
>  }
@mieubrisse Did you mean to remove this line? I believe we want to keep the last line?
I approved this PR (as it was a minor issue) and it auto-merged, my mistake.